# Generated by Django 3.0.5 on 2024-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
